# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

alias ls='ls --color'
alias ll='ls -l --color'
if [[ -z "$PATH" ]]; then
	PATH=/g/pkg/bin:/opt/bin
else
	PATH=/g/pkg/bin:/opt/bin:$PATH
fi
export PATH
if [[ -z "$LD_LIBRARY_PATH" ]]; then
	LD_LIBRARY_PATH=/g/pkg/lib
else
	LD_LIBRARY_PATH=/g/pkg/lib:$LD_LIBRARY_PATH
fi
export LD_LIBRARY_PATH
if [[ -z "$PYTHONPATH" ]]; then
	PYTHONPATH=/g/pkg/lib/python3.6/site-packages/
else
	PYTHONPATH=/g/pkg/lib/python3.6/site-packages/:$PYTHONPATH
fi
export PYTHONPATH
if [[ -z "$PKG_CONFIG_PATH" ]]; then
	PKG_CONFIG_PATH=/g/pkg/lib/pkgconfig
else
	PKG_CONFIG_PATH=/g/pkg/lib/pkgconfig:$PKG_CONFIG_PATH
fi
export PKG_CONFIG_PATH
